---
extends: default

yaml-files:
    - '*.ksy'

ignore: |
    outputs/

rules:
    # The ksy style guide, for whatever reason, says don't use this.
    # Dunno why. Seems silly.
    document-start: disable

    # it's 2021, can't we at least use -wide- dumb terminals as a
    # default for screen width?
    line-length: disable
    #     max: 132
    #    level: warning

    indentation:
        spaces: 4

    # spacing inside brackets and braces is good, yo
    brackets:
        max-spaces-inside: 1

    braces:
        max-spaces-inside: 1

    # Sometimes a tiny extra bit of spacing is useful
    empty-lines:
        max: 2

    # don't check line endings, git will take care of it
    new-lines: disable

    # default of VSCode, why argue?
    comments:
        min-spaces-from-content: 1
